tests = [ {'description': 'PINA: 0x00 => PORTB: 0x40',
    'steps': [ {'inputs': [('PINA',0x00)], 'iterations': 5 } ],
    'expected': [('PORTB',0x40)],
    },
    {'description': 'PINA: 0x01 => PORTB: 0x60',
    'steps': [ {'inputs': [('PINA',0x01)], 'iterations': 5 } ],
    'expected': [('PORTB',0x01)],
    },
    {'description': 'PINA: 0x03 => PORTB: 0x70',
    'steps': [ {'inputs': [('PINA',0x03)], 'iterations': 5 } ],
    'expected': [('PORTB',0x70)],
    },
    {'description': 'PINA: 0x07 => PORTB: 0x3C',
    'steps': [ {'inputs': [('PINA',0x07)], 'iterations': 5 } ],
    'expected': [('PORTB',0x3C)],
    },
    {'description': 'PINA: 0x0F => PORTB: 0x3F',
    'steps': [ {'inputs': [('PINA',0x0F)], 'iterations': 5 } ],
    'expected': [('PORTB',0x3F)],
    },
    {'description': 'PINA: 0x50 => PORTB: 0xC0',
    'steps': [ {'inputs': [('PINA',0x0F)], 'iterations': 5 } ],
    'expected': [('PORTB',0x3F)],
    },
    {'description': 'PINA: 0x70 => PORTB: 0x40',
    'steps': [ {'inputs': [('PINA',0x70)], 'iterations': 5 } ],
    'expected': [('PORTB',0x40)],
    },
    {'description': 'PINA: 0x5F => PORTB: 0xBF',
    'steps': [ {'inputs': [('PINA',0x0F)], 'iterations': 5 } ],
    'expected': [('PORTB',0x3F)],
    }
    ]
#watch = ['PORTB']

